@SongCollection = http://localhost:8004

GET {{SongCollection}}/


###

GET {{SongCollection}}/

###

GET {{SongCollection}}/


###

POST {{SongCollection}}/ HTTP/1.1
content-type: application/json

{
  "login": "pookiepew",
  "_id": "60295eec963275a423579545"
}