@MongoDB = http://localhost:8003

GET {{MongoDB}}/streamer/get
?login=pookiepew


###

GET {{MongoDB}}/streamer/get-all

###

GET {{MongoDB}}/streamer/get-refresh_token
?login=pookiepew


###

POST {{MongoDB}}/streamer/adduser HTTP/1.1
content-type: application/json

{
  "login": "pookiepew",
  "_id": "60295eec963275a423579545"
}

###

GET {{MongoDB}}/song

###

POST {{MongoDB}}/streamer/add-song HTTP/1.1
content-type: application/json

{
  "streamer": "pookiepew",
  "title": "requestable",
  "songId": "5fb1a44827e6bf00d2ff9d20"
}

###

GET {{MongoDB}}/streamer/get-songlist
?streamer=pookiepew
&title=requestable

###

GET {{MongoDB}}/streamer/get-songlist-titles
?streamer=pookiepew

###

POST {{MongoDB}}/streamer/remove-song HTTP/1.1
content-type: application/json

{
  "streamer": "pookiepew",
  "title": "requestable",
  "songId": "5fb1a44827e6bf00d2ff9d20"
}